HairSalon/Controllers/AppointmentsController.cs
using Microsoft.EntityFrameworkCore;
using Microsoft.AspNetCore.Mvc;
using HairSalon.Models;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace HairSalon.Controllers;

public class AppointmentsController : Controller
{
    private readonly HairSalonContext _db;

    public AppointmentsController(HairSalonContext db)
    {
        _db = db;
    }

    public ActionResult Index()
    {
        List<Appointment> model = _db.Appointments
            .Include(appointment => appointment.Client)
            .ThenInclude(client => client.Stylist)
            .ToList();
        ViewBag.PageTitle = "All appointments";
        return View(model);
    }

    public ActionResult Create()
    {
        ViewBag.ClientId = new SelectList(_db.Clients, "ClientId", "Name");
        ViewBag.PageTitle = "Add an appointment";
        return View();
    }

    [HttpPost]
    public ActionResult Create(Appointment appointment)
    {
        if (appointment.ClientId == 0)
        {
            return RedirectToAction("create");
        }

        List<Appointment> conflictCheck = _db.Appointments
            .Where(a => a.ClientId == appointment.ClientId)
            .ToList();

        if (conflictCheck.Any(a => a.Time == appointment.Time) && conflictCheck.Any(a => a.Date == appointment.Date))
        {
            return RedirectToAction("create");
        }
        _db.Appointments.Add(appointment);
        _db.SaveChanges();
        return RedirectToAction("index");
    }

    public ActionResult Delete(int id)
    {
        Appointment appt = _db.Appointments.FirstOrDefault(appt => appt.AppointmentId == id);
        ViewBag.PageTitle = "Cancel appointment";
        ViewBag.Details = appt;
        ViewBag.Client = _db.Clients.FirstOrDefault(client => client.ClientId == appt.ClientId);
        return View(appt);
    }

    [HttpPost, ActionName("Delete")]
    public ActionResult ConfirmDelete(int id)
    {
        Appointment appt = _db.Appointments.FirstOrDefault(appt => appt.AppointmentId == id);
        _db.Appointments.Remove(appt);
        _db.SaveChanges();
        return RedirectToAction("Index");
    }
}

HairSalon/Controllers/ClientsController.cs
using Microsoft.EntityFrameworkCore;
using Microsoft.AspNetCore.Mvc;
using HairSalon.Models;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace HairSalon.Controllers;

public class ClientsController : Controller
{
    private readonly HairSalonContext _db;

    public ClientsController(HairSalonContext db)
    {
        _db = db;
    }

    public ActionResult Index()
    {
        List<Client> model = _db.Clients
            .Include(client => client.Stylist)
            .ToList();
        ViewBag.PageTitle = "All clients";
        return View(model);
    }

    public ActionResult Create()
    {
        ViewBag.StylistId = new SelectList(_db.Stylists, "StylistId", "Name");
        ViewBag.PageTitle = "Add a client";
        return View();
    }


    [HttpPost]
    public ActionResult Create(Client client)
    {
        if (client.StylistId == 0)
        {
            return RedirectToAction("create");
        }
        _db.Clients.Add(client);
        _db.SaveChanges();
        return RedirectToAction("Index");
    }

    public ActionResult Details(int id)
    {
        Client client = _db.Clients
            .Include(client => client.Stylist)
            .Include(client => client.Appointments)
            .FirstOrDefault(client => client.ClientId == id);
        ViewBag.PageTitle = "Client details";
        return View(client);
    }

    public ActionResult Edit(int id)
    {
        Client client = _db.Clients.FirstOrDefault(client => client.ClientId == id);
        ViewBag.StylistId = new SelectList(_db.Stylists, "StylistId", "Name");
        ViewBag.PageTitle = "Edit client info";
        return View(client);
    }

    [HttpPost]
    public ActionResult Edit(Client client)
    {
        _db.Clients.Update(client);
        _db.SaveChanges();
        return RedirectToAction("Index");
    }

    public ActionResult Delete(int id)
    {
        Client client = _db.Clients.FirstOrDefault(client => client.ClientId == id);
        ViewBag.PageTitle = "Remove client";
        return View(client);
    }

    [HttpPost, ActionName("Delete")]
    public ActionResult ConfirmDelete(int id)
    {
        Client client = _db.Clients.FirstOrDefault(client => client.ClientId == id);
        _db.Clients.Remove(client);
        _db.SaveChanges();
        return RedirectToAction("Index");
    }
}

HairSalon/Controllers/SearchController.cs
using Microsoft.EntityFrameworkCore;
using Microsoft.AspNetCore.Mvc;
using HairSalon.Models;

namespace HairSalon.Controllers;

public class SearchController : Controller
{
    private readonly HairSalonContext _db;
    public SearchController(HairSalonContext db)
    {
        _db = db;
    }

    public async Task<ActionResult> Index(string searchType, string searchTerm)
    {
        switch (searchType)
        {
            case "client":
                List<Client> clientResults = await _db.Clients
                    .Where(client => client.Name.Contains(searchTerm))
                    .Include(client => client.Stylist)
                    .ToListAsync();
                return View(clientResults);
            default:
                List<Stylist> stylistResults = await _db.Stylists
                    .Where(stylist => stylist.Name.Contains(searchTerm))
                    .ToListAsync();
                return View(stylistResults);
        }
    }
}

HairSalon/Controllers/StylistsController.cs
using Microsoft.EntityFrameworkCore;
using Microsoft.AspNetCore.Mvc;
using HairSalon.Models;

namespace HairSalon.Controllers;

public class StylistsController : Controller
{
    private readonly HairSalonContext _db;
    public StylistsController(HairSalonContext db)
    {
        _db = db;
    }
    public ActionResult Index()
    {
        List<Stylist> model = _db.Stylists.ToList();
        ViewBag.PageTitle = "All stylists";
        return View(model);
    }

    public ActionResult Create()
    {
        ViewBag.PageTitle = "Add new stylist";
        return View();
    }

    [HttpPost]
    public ActionResult Create(Stylist stylist)
    {
        _db.Stylists.Add(stylist);
        _db.SaveChanges();
        return RedirectToAction("Index");
    }

    public ActionResult Details(int id)
    {
        Stylist thisStylist = _db.Stylists
            .Include(stylist => stylist.Clients)
            .FirstOrDefault(stylist => stylist.StylistId == id);
        ViewBag.PageTitle = "Stylist details";
        return View(thisStylist);

    }

    public ActionResult Edit(int id)
    {
        Stylist thisStylist = _db.Stylists.FirstOrDefault(stylist => stylist.StylistId == id);
        ViewBag.PageTitle = "Edit stylist info";
        return View(thisStylist);
    }

    [HttpPost]
    public ActionResult Edit(Stylist stylist)
    {
        _db.Stylists.Update(stylist);
        _db.SaveChanges();
        return RedirectToAction("Index");
    }

    public ActionResult Delete(int id)
    {
        Stylist thisStylist = _db.Stylists.FirstOrDefault(stylist => stylist.StylistId == id);
        ViewBag.PageTitle = "Remove stylist";
        return View(thisStylist);
    }

    [HttpPost, ActionName("Delete")]
    public ActionResult DeleteConfirmed(int id)
    {
        Stylist thisStylist = _db.Stylists.FirstOrDefault(Stylist => Stylist.StylistId == id);
        _db.Stylists.Remove(thisStylist);
        _db.SaveChanges();
        return RedirectToAction("Index");
    }
}

HairSalon/Views/Shared/_Header.cshtml
<div class="header">
    <div class="logo">
        <a href="/">
            <img src="~/images/logo.png" alt="Eau Claire's logo">
        </a>
    </div>
    <div class="title">
        <h1>Eau Claire's</h1>
        <h4>Stylist and Client Management Tool</h4>
        <div class="nav-buttons">
            @using (Html.BeginForm("Index", "Stylists", FormMethod.Get))
            {
                <input class="button" type="submit" value="View stylists">
            }

            @using (Html.BeginForm("Index", "Clients", FormMethod.Get))
            {
                <input class="button" type="submit" value="View clients">
            }

            @using (Html.BeginForm("Index", "Appointments", FormMethod.Get))
            {
                <input class="button" type="submit" value="View appointments">
            }
        </div>
    </div>

    <div class="search-bar">
        @using (Html.BeginForm("Index", "Search", FormMethod.Get))
        {
            @Html.Label("searchType", "Search for:")
            @Html.RadioButton("searchType", "stylists", true, new { id = "stylistRadio" }) <label for="stylistRadio">Stylists</label>
            @Html.RadioButton("searchType", "client", new { id = "clientRadio" }) <label for="clientRadio">Clients</label>
            @Html.TextBox("searchTerm")

            <input class="button" type="submit" value="Search">
        }
    </div>
</div>

HairSalon/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>

<head>
    <meta charset="utf-8">
    <title>@ViewBag.PageTitle</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65" crossorigin="anonymous">
    <link rel="stylesheet" href="~/css/styles.css" asp-append-version="true" />
</head>

<body>
    @await Html.PartialAsync("_Header")
    @RenderBody()
</body>

</html>